version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_container"
    ports:
      - 8080:8080
    depends_on:
      - web
  web:
    image: web
    build:
      context: ./web
    container_name: "web_container"
    ports:
      - 8001:8001
    command: sh -c "cd /app/src && gunicorn --reload hospitalmanagement.wsgi --bind 0.0.0.0:8001 --workers 4 --threads 4 --timeout 120"
    env_file:
      - "./api/.env"
    depends_on:
      - postgres
